In [1]:
import ipyvolume as ipv
from scipy.spatial import Delaunay
import numpy as np

In [16]:
points = np.array([[0, 0,1], [0, 1,2], [1, 0,3], [1, 1,1]])
points[:,:2]

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [27]:
tri = Delaunay(points[:,:2])
triangles = tri.simplices
points[tri.simplices]

array([[[1, 1, 1],
        [0, 1, 2],
        [0, 0, 1]],

       [[1, 0, 3],
        [1, 1, 1],
        [0, 0, 1]]])

In [31]:
triangle_points = points[tri.simplices]
x = points[:,0]
y = points[:,1]
z = points[:,2]
x

array([0, 0, 1, 1])

In [32]:
ipv.figure()
# we draw the tetrahedron
mesh = ipv.plot_trisurf(x, y, z, triangles=triangles, color='orange')
ipv.show()